variables:
  GIT_STRATEGY: none
  PROJECT_NAME: farapay-landing

stages:
  - production

production:
  only:
    - master
  stage: production
  tags:
    - master
  script:
    - "cd /var/www/projects/farapay-landing/"
    - 'git config --global user.name "m.gerami"'
    - 'git config --global user.email "m.gerami@mobtakerteam.com"'
    - "git stash"
    - "git fetch origin"
    - "git reset --hard origin/master"
    - "pnpm install"
    - "pnpm run build"
    - "npx pm2 delete 0"
    - npx pm2 start "pnpm run start" --name farapay-landing
